import { ISynonyms } from './synonymize';

export const synonyms: ISynonyms = {
  こうげきりょく: { type: 'primitive', name: 'atk' },
  // ばしょ: { type: 'primitive', name: 'location'},
  マップ: { type: 'primitive', name: 'mapName' },
  ひだりから: { type: 'primitive', name: 'mapX' },
  うえから: { type: 'primitive', name: 'mapY' },
  おかね: { type: 'primitive', name: 'money' },
  みえやすさ: { type: 'primitive', name: 'opacity' },
  ぶつかるか: { type: 'primitive', name: 'collisionFlag' },
  かんつうするかいすう: { type: 'primitive', name: 'penetrate' },
  たいりょく: { type: 'primitive', name: 'hp' },
  なにをしているか: { type: 'primitive', name: 'behavior' },
  ベクトル: { type: 'primitive', name: 'forward' },
  むき: { type: 'primitive', name: 'direction' },
  なかま: { type: 'primitive', name: 'family' },
  ダメージ: { type: 'primitive', name: 'damage' },
  あるくはやさ: { type: 'primitive', name: 'speed' },
  マップのはしにぶつかるか: { type: 'primitive', name: 'collideMapBoader' },
  たいりょくがみえるか: { type: 'primitive', name: 'showHpLabel' },
  なまえ: { type: 'primitive', name: 'name' },
  スキル: { type: 'primitive', name: 'skill' },
  みえるはんい: { type: 'primitive', name: 'fieldOfView' },
  みえるきょり: { type: 'primitive', name: 'lengthOfView' },
  むてきか: { type: 'primitive', name: 'isInvincible' },
  おや: { type: 'primitive', name: 'parent' },
  こうげきする: { type: 'function', name: 'attack' },
  あるく: { type: 'function', name: 'walk' },
  みぎにあるく: { type: 'function', name: 'walkRight' },
  ひだりにあるく: { type: 'function', name: 'walkLeft' },
  いく: { type: 'function', name: 'locate' },
  まつ: { type: 'function', name: 'wait' },
  しょうかんする: { type: 'function', name: 'summon' },
  へんしんする: { type: 'function', name: 'transform' },
  みつける: { type: 'function', name: 'find' },
  とんでいく: { type: 'function', name: 'flyToward' },
  おとをならす: { type: 'function', name: 'se' },
  はなす: { type: 'function', name: 'talk' },
  みためをかえる: { type: 'function', name: 'costume' },
  メッセージする: { type: 'function', name: 'message' },
  きえる: { type: 'function', name: 'destroy' },
  おいかける: { type: 'function', name: 'chase' },
  ふりむく: { type: 'function', name: 'faceTo' },
  テレポートランダム: { type: 'function', name: 'teleportRandom' },
  むきをかえる: { type: 'function', name: 'turn' }
};
