import { ISynonyms } from './synonymize';

export const synonyms: ISynonyms = {
  こうげきりょく: 'atk',
  // ばしょ: 'location',
  マップ: 'mapName',
  ひだりから: 'mapX',
  うえから: 'mapY',
  おかね: 'money',
  みえやすさ: 'opacity',
  ぶつかるか: 'collisionFlag',
  かんつうするかいすう: 'penetrate',
  たいりょく: 'hp',
  なにをしているか: 'behavior',
  ベクトル: 'forward',
  むき: 'direction',
  なかま: 'family',
  ダメージ: 'damage',
  あるくはやさ: 'speed',
  マップのはしにぶつかるか: 'collideMapBoader',
  たいりょくがみえるか: 'showHpLabel',
  なまえ: 'name',
  スキル: 'skill',
  みえるはんい: 'fieldOfView',
  みえるきょり: 'lengthOfView',
  むてきか: 'isInvincible',
  おや: 'parent',
  こうげきする: 'attack',
  あるく: 'walk',
  みぎにあるく: 'walkRight',
  ひだりにあるく: 'walkLeft',
  いく: 'locate',
  まつ: 'wait',
  しょうかんする: 'summon',
  へんしんする: 'transform',
  みつける: 'find',
  とんでいく: 'flyToward',
  おとをならす: 'se',
  はなす: 'talk',
  みためをかえる: 'costume',
  メッセージする: 'message',
  きえる: 'destroy',
  おいかける: 'chase',
  ふりむく: 'faceTo',
  テレポートランダム: 'teleportRandom',
  むきをかえる: 'turn'
};
