name: Deploy Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'packages/docs/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
          working-directory: packages/docs

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: |
          cd packages/docs
          npm install
          bundle install

      - name: Build documentation
        run: |
          npm run build -- --filter=@hackforplay/docs

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: packages/docs/_site
          branch: gh-pages
          repository-name: hackforplay/common
