# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Release

on:
  push:
    branches: '*'
    tags: 'v*'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Setup gcloud environment
      uses: GoogleCloudPlatform/github-actions@0.1.2
      with:
        # The service account key which will be used for authentication.
        service_account_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
      env:
        CI: true
    - name: Run semantic-release
      run: npx semantic-release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    - name: Upload
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        PATCH_VERSION=${GITHUB_REF/refs\/tags\/v/}
        MINOR_VERSION=${PATCH_VERSION%.*}
        echo $PATCH_VERSION
        echo $MINOR_VERSION
        # https://bit.ly/2xzjGVO
        gsutil cp -r dist gs://cdn.hackforplay.xyz/common/${PATCH_VERSION}
        gsutil cp -r dist/** gs://cdn.hackforplay.xyz/common/${MINOR_VERSION}
